# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN python -m pip install --upgrade pip

# Install project dependencies using pip with pip install .
# Using --ignore-installed to avoid conflicts
RUN pip install --no-cache-dir .

# Expose port if needed (default 8000, configurable by user if server uses it)
EXPOSE 8000

# Set entrypoint to launch the server
ENTRYPOINT ["python", "main.py"]
